apiVersion: apps/v1
kind: Deployment
metadata:
  name: myalpine-deployment
  namespace: test-argo
  labels:
    apps: myalpine
spec:
  selector:
    matchLabels:
      app: myalpine
  replicas: 2
  template:
    metadata:
      labels:
        app: myalpine
    spec:
      containers:
      - name: myalpine
        image: alpine:3.14
